#!/usr/bin/env bash
# Configures localhost and facebook.com IP addresses

sed -i 's/^127\.0\.0\.1[[:space:]]\+localhost/127.0.0.2\tlocalhost/' /etc/hosts
printf '8.8.8.8\tfacebook.com\n' >> /etc/hosts
